spring.application.name=Auth-Service
server.port=9040

spring.datasource.url=jdbc:postgresql://localhost:5433/authDB
spring.datasource.username=postgres
spring.datasource.password=AamirH23@1704
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

## JWT Secrets and Eureka Config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
jwt.SecretKey=nnfjikwoflxpckujndiofhnuoiefnwpoiirpogkdnfxkzlhnbqpokgriljrguudiouhefoijgoihef893583598u784wgdkuhviphiugh0983547u5guhruig893ytuheuirfjghsdifjsoeif308u