spring.application.name=Warehouse-Service
spring.config.import=configserver:http://localhost:9080
## Server Config
server.port=9060

## Inventory DB Properties
spring.datasource.url=jdbc:postgresql://localhost:5433/warehouseDB
spring.datasource.username=postgres
spring.datasource.password=AamirH23@1704
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

## Eureka Server
## All services will go here to register themselves
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true